version: '3'
services:
  frontend:
    image: node:20
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
    working_dir: /app
    command: yarn dev

  backend:
    image: node:20
    volumes:
      - ../backend:/app
    working_dir: /app
    command: yarn dev